<a href="https://colab.research.google.com/github/2303A52328/Gen-AI-2428/blob/main/2303A52428_GEN_AI_Week_8_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adadelta

# Initialize the model
model = Sequential()

# Adding the hidden layers as per the architecture
model.add(Dense(16, input_dim=11, activation='relu'))  # 16 neurons in the first hidden layer
model.add(Dense(20, activation='relu'))  # 20 neurons in the second hidden layer
model.add(Dense(25, activation='relu'))  # 25 neurons in the third hidden layer
model.add(Dense(10, activation='relu'))  # 10 neurons in the fourth hidden layer

# Output layer - assuming binary classification (1 neuron with sigmoid activation)
model.add(Dense(1, activation='sigmoid'))  # Modify this if your dataset requires more output neurons.

# Compile the model with the specified optimizer and metric
model.compile(loss='binary_crossentropy', optimizer=Adadelta(), metrics=['accuracy'])

# Print the summary of the model architecture
model.summary()


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 16)                  │             192 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 20)                  │             340 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 25)                  │             525 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 10)                  │             260 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 1)                   │              11 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,328 (5.19 KB)

 Trainable params: 1,328 (5.19 KB)

 Non-trainable params: 0 (0.00 B)

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

# Load the dataset
url = '/content/winequality-red.csv'
data = pd.read_csv(url)

# Assuming the target variable is in the last column, adjust according to your dataset
X = data.iloc[:, :-1].values  # Features
y = data.iloc[:, -1].values   # Target variable (wine quality)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train the model
history = model.fit(X_train, y_train, epochs=100, batch_size=64, validation_data=(X_test, y_test))

# Save the model to an H5 file
model.save('wine_quality_model.h5')

# Evaluate the model on the test set
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f'Test Accuracy: {test_accuracy * 100:.2f}%')

# Make predictions
y_pred = (model.predict(X_test) > 0.5).astype("int32")

# Print classification report and confusion matrix
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - accuracy: 0.0000e+00 - loss: 0.9113 - val_accuracy: 0.0000e+00 - val_loss: 0.9497
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0000e+00 - loss: 0.9343 - val_accuracy: 0.0000e+00 - val_loss: 0.9473
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0000e+00 - loss: 0.9284 - val_accuracy: 0.0000e+00 - val_loss: 0.9448
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0000e+00 - loss: 0.9351 - val_accuracy: 0.0000e+00 - val_loss: 0.9423
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0000e+00 - loss: 0.9248 - val_accuracy: 0.0000e+00 - val_loss: 0.9398
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0000e+00 - loss: 0.9021 - val_accuracy: 0.0000e+00 - val_loss: 0.9372
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0000e+00 - loss: 0.9107 - val_accuracy: 0.0000e+00 - val_loss: 0.9346
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - 

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0000e+00 - loss: 0.6382  
Test Accuracy: 0.00%
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step  

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           1       0.00      0.00      0.00       0.0
           3       0.00      0.00      0.00       1.0
           4       0.00      0.00      0.00      10.0
           5       0.00      0.00      0.00     130.0
           6       0.00      0.00      0.00     132.0
           7       0.00      0.00      0.00      42.0
           8       0.00      0.00      0.00       5.0

    accuracy                           0.00     320.0
   macro avg       0.00      0.00      0.00     320.0
weighted avg       0.00      0.00      0.00     320.0


Confusion Matrix:
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0]
 [44 86  0  0  0  0  0  0]
 [58 74  0  0  0  0  0  0]
 [2

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_

In [3]:
from keras.models import load_model
import numpy as np
from sklearn.preprocessing import StandardScaler

# Load the saved model
model = load_model('wine_quality_model.h5')

# Example for making a prediction
# Assuming the input is a numpy array of features similar to the dataset
input_data = np.array([[7.4, 0.7, 0.0, 1.9, 0.076, 11.4, 34.0, 0.997, 3.51, 0.56, 9.4]])  # Example input data

# Normalize the input data
scaler = StandardScaler()
input_data_scaled = scaler.fit_transform(input_data)

# Predict the quality of wine (binary classification)
prediction = model.predict(input_data_scaled)

# Output the prediction
print(f'Predicted Quality: {"Good" if prediction > 0.5 else "Bad"}')


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step
Predicted Quality: Good
